import Link from "next/link";
import { Activity, AlertOctagon } from "lucide-react";

const footerLinks = {
  Product: [
    { label: "How it works", href: "/#how-it-works" },
    { label: "AI Agents", href: "/#ai-agents" },
    { label: "Summary Preview", href: "/#summary" },
    { label: "Demo", href: "/demo" },
  ],
  Company: [
    { label: "For Clinics", href: "/clinics" },
    { label: "Contact", href: "/contact" },
  ],
  Legal: [
    { label: "Safety Policy", href: "/safety" },
    { label: "Privacy", href: "/safety" },
    { label: "Terms", href: "/safety" },
  ],
};

export default function Footer() {
  return (
    <footer className="bg-white border-t border-border">
      {/* Emergency notice */}
      <div className="bg-amber-50 border-b border-amber-100">
        <div className="container-custom py-3">
          <div className="flex items-center gap-2 text-xs text-amber-800" role="alert">
            <AlertOctagon className="w-4 h-4 text-amber-600 flex-shrink-0" aria-hidden="true" />
            <strong>Emergency:</strong>&nbsp;If you may be experiencing a medical emergency, contact local emergency services immediately. Do not use this platform for emergencies.
          </div>
        </div>
      </div>

      <div className="container-custom py-14">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div className="col-span-2 md:col-span-1">
            <Link href="/" className="flex items-center gap-2 mb-4 group" aria-label="MedNavigator AI home">
              <div className="w-8 h-8 rounded-lg gradient-brand flex items-center justify-center shadow-brand">
                <Activity className="w-4 h-4 text-white" aria-hidden="true" />
              </div>
              <span className="font-semibold text-sm">
                MedNavigator <span className="gradient-text">AI</span>
              </span>
            </Link>
            <p className="text-xs text-muted-foreground leading-relaxed max-w-[200px]">
              AI medical navigation before the doctor visit. Not a diagnostic tool.
            </p>
          </div>

          {/* Links */}
          {Object.entries(footerLinks).map(([section, links]) => (
            <div key={section}>
              <h4 className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">
                {section}
              </h4>
              <ul className="space-y-2.5">
                {links.map((link) => (
                  <li key={link.label}>
                    <Link
                      href={link.href}
                      className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="border-t border-border mt-12 pt-8 space-y-4">
          {/* Main disclaimer */}
          <div className="rounded-xl bg-muted border border-border p-4">
            <p className="text-xs text-muted-foreground leading-relaxed">
              <strong>Medical Disclaimer:</strong> MedNavigator AI is not a licensed medical device, diagnostic tool, or healthcare provider. The content and outputs generated by this platform are for informational and navigation purposes only. They do not constitute medical advice, diagnosis, or treatment recommendations. Always consult a qualified healthcare professional for medical decisions. In case of emergency, contact local emergency services immediately.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs text-muted-foreground">
            <p>© {new Date().getFullYear()} MedNavigator AI. All rights reserved.</p>
            <p>Not intended for emergency use. Not a diagnostic tool.</p>
          </div>
        </div>
      </div>
    </footer>
  );
}
